### ISSUE TITLE
[ERR]似乎由于原作者删库 无法正常下载RCC导致无法正常运行

### ISSUE THREAD

**Issue by qwq233** [Elepover/RevokeChinaCertGUI#2]
![Err.png](https://i.loli.net/2020/02/04/y2jKHFTLdO3mQn9.png)
如上

**Comment by Elepover** [comment]
[最近的 Release](https://github.com/Elepover/RevokeChinaCertGUI/releases/download/initial/Release.zip) 包含了最后一版可用的 RCC
